name: Build Container Artifacts
on: 
  push:
    branches:
      - 'main'

jobs:
   build:
    name: Build Base Image
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main
          prefix: v
          major-identifier: /[major,breaking]
          minor-identifier: /[minor,hotfix,feature]
          dev-branch: dev
    
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}