name: Git Tag Example
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  tag:
    name: TAG the Build
    runs-on: ubuntu-latest
    #if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set env
        run: echo "latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
        
      - name: Test
        run: |
          echo $latest_tag
          echo ${{ env.latest_tag }}
    
