name: Git Tag Example
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  tag:
    name: TAG the Build
    runs-on: ubuntu-latest
    #if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: octokit/rest.js  # The repository to scan.
        id: git_tag  # The step ID to refer to later.

      - name: Print tag
        run: echo "Repo is at version ${{ steps.git_tag.outputs.tag }}"
