name: Git Tag Example
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  tag:
    name: TAG the Build
    runs-on: ubuntu-latest
    #if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
    
