name: Git Tag Example
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  tag:
    name: TAG the Build
    runs-on: ubuntu-latest
    #if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print tag
        run: | 
           chmod +x .github/workflows/get_git_tag.sh
           ./.github/workflows/get_git_tag.sh
