name: Git Tag Example
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  tag:
    name: TAG the Build
    runs-on: ubuntu-latest
    #if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: Print tag
        run: |
           echo "GIT_TAG=`echo $(git describe)`" >> $GITHUB_ENV
     
      - name: Test
        run: echo $GIT_TAG
